// Styles auth — interface simple type SaaS

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const formStyles: Record<string, any> = {
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    width: '100%',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    width: '100%',
  },
  label: {
    display: 'none',
  },
  labelIcon: {
    display: 'none',
  },
  input: {
    padding: '15px 18px',
    borderRadius: '16px',
    border: '1.5px solid #dde3ee',
    fontSize: '15px',
    fontFamily: 'inherit',
    transition: 'box-shadow 0.2s ease, background-color 0.2s ease, border-color 0.2s ease',
    backgroundColor: '#ffffff',
    color: '#0f172a',
    width: '100%',
    boxSizing: 'border-box',
    boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04)',
  },
  inputFocus: {
    outline: 'none',
    backgroundColor: '#ffffff',
    borderColor: '#38bdf8',
    boxShadow: '0 0 0 3px rgba(56, 189, 248, 0.2)',
  },
  inputError: {
    borderColor: '#f87171',
    backgroundColor: '#fef2f2',
    boxShadow: '0 0 0 3px rgba(248, 113, 113, 0.15)',
  },
  inputWrapper: {
    position: 'relative',
    width: '100%',
  },
  inputGlow: {
    display: 'none',
  },
  errorText: {
    color: '#b91c1c',
    fontSize: '12px',
    fontWeight: '500',
  },
  success: {
    color: '#065f46',
    fontWeight: '600',
    padding: '12px 14px',
    background: '#ecfdf5',
    borderRadius: '16px',
    fontSize: '14px',
    border: '1px solid #a7f3d0',
    width: '100%',
    boxSizing: 'border-box',
  },
  error: {
    color: '#991b1b',
    fontWeight: '600',
    padding: '12px 14px',
    background: '#fef2f2',
    borderRadius: '16px',
    fontSize: '14px',
    border: '1px solid #fecaca',
    width: '100%',
    boxSizing: 'border-box',
  },
  button: (loading: boolean) => ({
    padding: '15px 24px',
    borderRadius: '16px',
    border: 'none',
    background: loading ? '#94a3b8' : '#2563eb',
    color: 'white',
    fontSize: '15px',
    fontWeight: '700',
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
    cursor: loading ? 'not-allowed' : 'pointer',
    opacity: loading ? 0.85 : 1,
    marginTop: '8px',
    transition: 'background 0.2s ease, box-shadow 0.2s ease, transform 0.2s ease',
    boxShadow: loading ? 'none' : '0 10px 24px rgba(37, 99, 235, 0.35)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '10px',
    width: '100%',
    boxSizing: 'border-box',
  }),
  buttonShine: {
    display: 'none',
  },
  infoBox: {
    padding: '12px 14px',
    background: '#eef2f7',
    borderRadius: '16px',
    fontSize: '13px',
    color: '#475569',
    lineHeight: 1.45,
    width: '100%',
    boxSizing: 'border-box',
  },
  required: {
    color: '#ef4444',
    marginLeft: '2px',
  },
  optional: {
    fontSize: '12px',
    color: '#94a3b8',
    fontWeight: '400',
  },
  forgotPassword: {
    textAlign: 'right' as const,
    marginTop: '2px',
  },
  forgotPasswordLink: {
    color: '#64748b',
    textDecoration: 'none',
    fontSize: '13px',
    fontWeight: '500',
  },
  rowBetween: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: '-4px',
  },
};
